leftnav:
- identifier: 8fae8df7-209e-321a-e453-264c3d63e1a2
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6199f8e7-db61-6ed4-44c1-3e48b937ae4c
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: d95607c9-ffe7-0176-0022-8040194db1cf
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2d58e487-a4db-8d96-c0b4-b154411f80d9
  name: Recitations
  pageRef: /pages/recitations
  weight: 40
- identifier: 112e5bd4-207b-9f8a-7e21-68d0eb184f06
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
